import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Footer } from "./component/Footer";
import { ToastContainer } from "react-toastify";
import { UserContext } from "./context/userContext";
import UserProvider from "./context/UserProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en"  >
      <body suppressHydrationWarning>
        <UserProvider>
          <ToastContainer />
          <Navbar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
